return {
    -- 'akinsho/git-conflict.nvim',
    -- -- event = { "BufReadPost", "BufWritePost", "BufNewFile" },
    -- lazy = false,
    -- dependencies = {
    --     'nvim-telescope/telescope.nvim'
    -- },
    -- keys = {
    --     {"<leader>gco", '<cmd>GitConflictChooseOurs<CR>', mode={"n"}, desc="Git conflicts: choose ours"},
    --     {"<leader>gct", '<cmd>GitConflictChooseTheirs<CR>', mode={"n"}, desc="Git conflicts: choose theirs"},
    --     {"<leader>gcb", '<cmd>GitConflictChooseBoth<CR>', mode={"n"}, desc="Git conflicts: choose both"},
    --     {"<leader>gc0", '<cmd>GitConflictChooseNone<CR>', mode={"n"}, desc="Git conflicts: choose none"},
    --     {"<leader>gcl", '<cmd>GitConflictListQf<CR>', mode={"n"}, desc="Git conflicts: list conflicts"},
    --     {"]x", '<cmd>GitConflictNextConflict<CR>', mode={"n"}, desc="Git conflicts: next conflict"},
    --     {"[x", '<cmd>GitConflictPrevConflict<CR>', mode={"n"}, desc="Git conflicts: previous conflict"},
    -- },
    -- opts = {
    --     default_mappings = false,
    --     list_opener = function() require('telescope.builtin').quickfix() end
    -- },
    -- version = "*",
    -- config = true
}
